### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift [updated your build matrix](https://github.com/seancheung/history/pull/29/commits/78d2972be3f9a39567c190a1d01f7b18a074faf0?w=1) for Laravel 10. However, since you are supporting older versions of Laravel, you need to add the following exclusions:

```yaml
exclude:
  - laravel: 10.*
    php-versions: 7.2
  - laravel: 10.*
    php-versions: 7.3
  - laravel: 10.*
    php-versions: 7.4
  - laravel: 10.*
    php-versions: 8.0
```

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/seancheung/history/pull/29/commits/78d2972be3f9a39567c190a1d01f7b18a074faf0?w=1) for Laravel 10. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/history.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "panoscape/history": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by KarimGeiger** [comment]
Reading the [Upgrade Guide](https://laravel.com/docs/10.x/upgrade#model-dates-property), it looks like the `$date` property on the Model has been removed. Therefore, [History.php:21](https://github.com/seancheung/history/blob/master/src/History.php#L21) would need to be removed and the `$casts` property needs to be merged with:

```php
protected $casts = [
    'meta' => 'array',
    'performed_at' => 'datetime'
];
```

**Comment by seancheung** [comment]
Thank you guys. A new release has been published.
Checkout [v2.5.0](../releases/tag/2.5.0)

**Pull request closed without merging**
